# Funções

In [1]:
import numpy as np

# declaração da função
def mega_sena():
  sorteio = np.random.choice(range(1,61), 6, replace=False)
  return sorteio

In [2]:
# chamada da função
mega_sena()

array([55, 60, 24, 19, 48, 37])

Passando argumento obrigatório para a função

In [3]:
def mega_sena(quantidade_de_numeros):
  sorteio = np.random.choice(range(1,61), quantidade_de_numeros, replace=False)
  return sorteio

In [4]:
mega_sena(6)

array([ 6, 10, 15, 17, 47, 35])

In [5]:
mega_sena(7)

array([59, 17, 58, 36, 38, 45, 33])

In [6]:
mega_sena(8)

array([27, 42, 36,  3, 22, 16, 10, 55])

Paasando um argumento com valor valor padrão

In [7]:
# argumentos obrigatórios devem vir antes de argumentos com valores padrão
def loteria(quantidade_de_numeros, intervalo=range(1,61)):
  sorteio = np.random.choice(intervalo, quantidade_de_numeros, replace=False)
  return sorteio

In [8]:
# mega sena com 6 números
loteria(6)

array([33, 27, 48, 35,  1, 29])

In [9]:
# quina com 5 números
loteria(5, range(1, 81))

array([ 5, 61, 12, 67, 30])

Restrição: não deixar usuário passar numeros < 5

In [10]:
def loteria(quantidade_de_numeros, intervalo=range(1,61)):
  if quantidade_de_numeros < 5:
    return 'Sorteio não deve conter menos de 5 números'
  sorteio = np.random.choice(intervalo, quantidade_de_numeros, replace=False)
  return sorteio

In [11]:
loteria(4)

'Sorteio não deve conter menos de 5 números'

Retonar mais de 1 valor

In [12]:
def loteria(quantidade_de_numeros, intervalo=range(1,61)):
  if quantidade_de_numeros < 5:
    return 'Sorteio não deve conter menos de 5 números'
  sorteio = np.random.choice(intervalo, quantidade_de_numeros, replace=False)
  return sorteio, 'boa sorte!'

In [13]:
# retorno é uma tupla
loteria(5)

(array([14,  3, 50, 56, 37]), 'boa sorte!')

In [14]:
loteria(4)

'Sorteio não deve conter menos de 5 números'

#Exercício 1: crie uma função que receba um número como parâmetro e calcule o fatorial do mesmo

In [ ]:
def fatorial(num):
  fat = 1
  for i in range(1, num + 1):
    fat *= i
  return fat

In [ ]:
fatorial(5)

120

Utilize a função factorial do pacote math

In [ ]:
from math import factorial

In [ ]:
factorial(5)

120

#Exercício 2: Crie uma função que receba o valor do raio de um círculo e retorne o valor da área do mesmo. Utilize o pacote math.


In [ ]:
import math
def area_circulo(raio):
  return math.pi * raio**2

In [ ]:
area_circulo(2)

12.566370614359172

Altere a função criada anteriormente para que ela retorne, além do valor da área do círculo, retorne também o diâmetro e o perímetro.


In [ ]:
def area_circulo(raio):
  area = math.pi * raio**2
  diametro = 2*raio
  perimetro = 2*math.pi*raio
  return area, diametro, perimetro

In [ ]:
area_circulo(4)

(50.26548245743669, 8, 25.132741228718345)

raio com valor padrao = 5

In [ ]:
def area_circulo(raio=5):
  area = math.pi * raio**2
  diametro = 2*raio
  perimetro = 2*math.pi*raio
  return area, diametro, perimetro

In [ ]:
area_circulo()

(78.53981633974483, 10, 31.41592653589793)

In [ ]:
area_circulo(3)

(28.274333882308138, 6, 18.84955592153876)

#Exercício 3: Função para LGN


In [ ]:
import numpy as np
def lgn(exp):
  cont = 0
  for i in range(exp):
    x = np.random.normal()
    if(x > -1 and x < 1):
        cont += 1
  return cont / exp

In [ ]:
print(lgn(10))
print(lgn(100))
print(lgn(1000))
print(lgn(10000))
print(lgn(100000))

0.8
0.72
0.689
0.6798
0.68225


Após validação da função, inclua um parâmetro opcional de intervalo a ser validado. O valor default deve ser -1 e 1.


In [ ]:
def lgn(exp, intervalo_inferior=-1, intervalo_superior=1):
  cont = 0
  for i in range(exp):
    x = np.random.normal()
    if(x > intervalo_inferior and x < intervalo_superior):
        cont += 1
  return cont / exp

In [ ]:
lgn(100000)

0.68332

In [ ]:
lgn(100000, 1, 2)

0.13798

In [ ]:
lgn(1000000, 2, 3)

0.021358