# Estruturas Condicionais

In [2]:
import numpy as np
#gerar um numero aleatoriamente com distribuicao normal
num = np.random.normal()
num

-1.1077718818002147

In [3]:
# verificar se num eh maior que 1
if num > 1:
  print('Maior que 1')
elif num > -1:
  print('Entre -1 e 1')
else:
  print('Menor ou igual a -1')

Menor ou igual a -1


# Estruturas de Repetição

In [ ]:
# WHILE
contador = 1
while(contador < 6):
  print('hello')
  contador += 1

hello
hello
hello
hello
hello


In [ ]:
# FOR
for i in [23, 45, 56]:
  print('hello' + str(i))

hello23
hello45
hello56


In [ ]:
for i in (1,2,3):
  print(i)

1
2
3


In [ ]:
for i in 'PUC':
  print(i)

P
U
C


In [ ]:
for i in range(4):
  print(i)

0
1
2
3


In [ ]:
for i in range(4, 9):
  print(i)

4
5
6
7
8


In [ ]:
for i in range(2):
  for j in range(3):
    print(str(i) + str(j))

00
01
02
10
11
12


# Exercícios

1. Imprima uma sequência de 25 números consecutivos.


In [ ]:
cont = 1
while cont <= 25:
  print(cont) 
  cont += 1

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25


In [ ]:
for i in range(25):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


2. Imprima a sequência acima 2 vezes. Dica: for dentro de for ou while dentro de while, etc...


In [ ]:
for n in range(2):
  for i in range(25):
    print(str(n) + ' ' + str(i))

0 0
0 1
0 2
0 3
0 4
0 5
0 6
0 7
0 8
0 9
0 10
0 11
0 12
0 13
0 14
0 15
0 16
0 17
0 18
0 19
0 20
0 21
0 22
0 23
0 24
1 0
1 1
1 2
1 3
1 4
1 5
1 6
1 7
1 8
1 9
1 10
1 11
1 12
1 13
1 14
1 15
1 16
1 17
1 18
1 19
1 20
1 21
1 22
1 23
1 24


3. Na sequência de 0 a 30, imprima somente os números pares. Dica: operador para pegar o resto de uma divisão: %


In [ ]:
for i in range(31):
  if i % 2 == 0:
    print(i)

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30


4. Mega Sena: 6 números entre 1 e 60 (1 sorteio). (usando uma estrutura de repetição e sem usar estruturas de repetição). Dica: função np.random.randint


In [ ]:
for num in range(6):
  print(np.random.randint(1,61))
  # pode gerar números repetidos

18
45
12
26
44
45


In [ ]:
np.random.randint(1,61, 6)  # pode gerar números repetidos

array([34, 48,  6,  6,  1, 11])

In [4]:
# não gera números repetidos
sorteio = []
while len(sorteio) < 6:
  dezena = np.random.randint(1,61)
  if dezena not in sorteio:
    sorteio.append(dezena)
sorteio

[24, 2, 21, 31, 6, 43]

OU

In [ ]:
# não gera números repetidos
np.random.choice(range(1,61), 6, replace=False)

array([37,  4,  6,  7, 41, 25])

OU

In [6]:
sorteio = set()
while len(sorteio) < 6:
  sorteio.add(np.random.randint(1,61))
sorteio

{5, 9, 11, 23, 38, 59}

5. Simule o resultado de um dado de 6 faces jogado 7 vezes. (usando uma estrutura de repetição e sem usar estruturas de repetição). Dica: função np.random.randint


In [ ]:
for dado in range(7):
  print(np.random.randint(1,7))

4
4
2
3
5
1
5


In [ ]:
np.random.randint(1,7, 7)

array([3, 3, 5, 2, 4, 1, 2])

In [7]:
np.random.choice(range(1,7), 7, True)

array([1, 3, 5, 5, 4, 3, 5])

Crie um script que calcule o fatorial de um número qualquer.


In [ ]:
num = 7

fat = 1
for i in range(1, num + 1):
  fat *= i

fat

5040

In [ ]:
import math
math.factorial(7)

5040

Lei dos grandes numeros

In [ ]:
exp = 100000
cont = 0

for i in range(exp):
  x = np.random.normal()
  if(x > -1 and x < 1):
      cont += 1

cont / exp

0.68102