# Exercício 2: Demonstrativo Financeiro

In [2]:
import numpy as np

In [3]:
receitas = np.array([14574.49, 7606.46, 18611.41, 19175.41, 8758.65, 8105.44, 11496.28, 9766.09, 10305.32, 18379.96, 10713.97, 15433.5])
custos = np.array([12051.82, 5695.07, 12319.2, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96])

In [4]:
# lucro de cada mes
lucro_mes = receitas - custos
lucro_mes

array([ 2522.67,  1911.39,  6292.21,  7085.69,   100.08,  7265.24,
        8210.55,  3944.97,  3328.39,  1761.35,   659.6 , 11629.54])

In [5]:
# lucro líquido (30%)
lucro_liquido = 0.7 * lucro_mes
lucro_liquido

array([1765.869, 1337.973, 4404.547, 4959.983,   70.056, 5085.668,
       5747.385, 2761.479, 2329.873, 1232.945,  461.72 , 8140.678])

In [6]:
# margem de lucro
margem = lucro_liquido / receitas
margem

array([0.12116163, 0.17589956, 0.23665843, 0.25866373, 0.00799849,
       0.62743886, 0.49993433, 0.28276199, 0.22608449, 0.06708094,
       0.04309514, 0.52746804])

In [7]:
# meses bons
lucro_medio = lucro_liquido.mean()
lucro_medio

3191.514666666666

In [8]:
meses_bons = lucro_liquido > lucro_medio
meses_bons

array([False, False,  True,  True, False,  True,  True, False, False,
       False, False,  True])

In [9]:
np.where(meses_bons)  # retorna idx dos verdadeiros

(array([ 2,  3,  5,  6, 11]),)

In [10]:
lucro_liquido[meses_bons] # retorna o lucro do meses bons

array([4404.547, 4959.983, 5085.668, 5747.385, 8140.678])

In [11]:
lucro_liquido[np.where(meses_bons)]  # retorna o lucro do meses bons

array([4404.547, 4959.983, 5085.668, 5747.385, 8140.678])

In [12]:
# Meses ruins
meses_ruins = np.where(meses_bons == False)
meses_ruins

(array([ 0,  1,  4,  7,  8,  9, 10]),)

In [13]:
lucro_liquido[meses_ruins]

array([1765.869, 1337.973,   70.056, 2761.479, 2329.873, 1232.945,
        461.72 ])

In [14]:
# melhor mes
lucro_liquido.max()  #valor do melhor mês

8140.678

In [17]:
np.where(lucro_liquido == lucro_liquido.max())

(array([11]),)

In [18]:
# pior mes
lucro_liquido.min()

70.05599999999994

In [19]:
np.where(lucro_liquido == lucro_liquido.min())

(array([4]),)