# Numpy
Manipulação de dados



In [31]:
import numpy as np

t1 = np.ones(4) # vetor com 4 '1's
t1

array([1., 1., 1., 1.])

In [32]:
t1.shape

(4,)

In [33]:
# tensor 3D
t2 = np.ones((4, 3, 2))
t2

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [34]:
t2.shape

(4, 3, 2)

In [35]:
t3 = np.random.random((4,3,2))
t3

array([[[0.74669578, 0.79020214],
        [0.44855047, 0.43933012],
        [0.58307067, 0.11458664]],

       [[0.71762302, 0.70638691],
        [0.1220032 , 0.22254756],
        [0.70855402, 0.20652216]],

       [[0.05582885, 0.92110012],
        [0.58088838, 0.23219759],
        [0.10651612, 0.09950113]],

       [[0.31606527, 0.60474283],
        [0.9271064 , 0.43032817],
        [0.72231193, 0.0242361 ]]])

In [36]:
t3.shape

(4, 3, 2)

Criar array fornecendo os valores

In [37]:
x = np.array([[1,2,3,4],[5,6,7,8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
x.shape

(2, 4)

In [39]:
x.size #num de elementos  

8

In [40]:
x.ndim #numero de dimensoes

2

In [41]:
x.dtype #tipo dos dados

dtype('int64')

In [42]:
x.sum() #soma de tds os elementos

36

In [43]:
x.max() #maior valor

8

In [44]:
x.min() #menor valor

1

acessar elementos dentro de array

In [45]:
# acessar o primeriro elemento
x[0,0]

1

In [46]:
# elemento da segunda linha e segunda coluna
x[1,1]

6

In [47]:
# multiplos elementos
x[0, 1:3] # inclusive:exclusive. entoa nao pega col de idx 3

array([2, 3])

##Operações com arrays

In [48]:
a = np.array([[1,2], [4,5]])
b = np.array([[10,20], [30,40]])

print(a)
print(b)

[[1 2]
 [4 5]]
[[10 20]
 [30 40]]


In [49]:
# Multiplicação (element-wise)
2 * a

array([[ 2,  4],
       [ 8, 10]])

In [50]:
2 + a

array([[3, 4],
       [6, 7]])

In [51]:
# Matricial
a.dot(b)

array([[ 70, 100],
       [190, 280]])