Vamos transformar as palavras em números para depois, fazermos o algoritmo de machine learning

In [10]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
# Exemplo de lista de documentos
documentos = ['o gato correu atrás do rato',
              'o rato tentou se esconder do gato',
              'o gato pegou o rato e comeu']

In [12]:
# Instanciando o objeto CountVectorizer
vetorizador = CountVectorizer()

# Ajustando o vetorizador aos documentos e transformando em matriz de contagem
matriz_contagem = vetorizador.fit_transform(documentos)

In [13]:
# transformando em um df a matriz de contagem
pd.DataFrame(matriz_contagem.toarray(), columns=vetorizador.get_feature_names_out())

atrás  comeu  correu  do  esconder  gato  pegou  rato  se  tentou
0      1      0       1   1         0     1      0     1   0       0
1      0      0       0   1         1     1      0     1   1       1
2      0      1       0   0         0     1      1     1   0       0

Tipos de Similaridade:

Similaridade por frequência
Similaridade por contexto

Exercício - Similaridade entre documentos

In [14]:
corpus = ['the weather is hot under the sun',
          'I make my hot chocolate with milk',
          'One hot enconding',
          'i will have a chai latte with milk',
          'There is a hot sale today']

In [15]:
cv = CountVectorizer(stop_words='english')
X = cv.fit_transform(corpus).toarray()
dt = pd.DataFrame(X, columns=cv.get_feature_names_out())
dt

chai  chocolate  enconding  hot  latte  make  milk  sale  sun  today   
0     0          0          0    1      0     0     0     0    1      0  \
1     0          1          0    1      0     1     1     0    0      0   
2     0          0          1    1      0     0     0     0    0      0   
3     1          0          0    0      1     0     1     0    0      0   
4     0          0          0    1      0     0     0     1    0      1   

   weather  
0        1  
1        0  
2        0  
3        0  
4        0

In [16]:
# Calculate the cosine similarity between all combinations of documents
from itertools import combinations
from sklearn.metrics.pairwise import cosine_similarity

In [18]:
# list all of the combinations of 5 take 2 as well as the pairs of phrases
pairs = list(combinations(range(len(corpus)), 2))
combos = [(corpus[a_index], corpus[b_index]) for (a_index, b_index) in pairs]

In [20]:
# calculate the cosine similarity for all pairs of phrases and sort by most similar
results = [cosine_similarity([X[a_index]], [X[b_index]]) for (a_index, b_index) in pairs]
sorted(zip(results, combos), reverse=True)

[(array([[0.40824829]]),
  ('the weather is hot under the sun', 'One hot enconding')),
 (array([[0.40824829]]), ('One hot enconding', 'There is a hot sale today')),
 (array([[0.35355339]]),
  ('I make my hot chocolate with milk', 'One hot enconding')),
 (array([[0.33333333]]),
  ('the weather is hot under the sun', 'There is a hot sale today')),
 (array([[0.28867513]]),
  ('the weather is hot under the sun', 'I make my hot chocolate with milk')),
 (array([[0.28867513]]),
  ('I make my hot chocolate with milk', 'i will have a chai latte with milk')),
 (array([[0.28867513]]),
  ('I make my hot chocolate with milk', 'There is a hot sale today')),
 (array([[0.]]),
  ('the weather is hot under the sun', 'i will have a chai latte with milk')),
 (array([[0.]]),
  ('i will have a chai latte with milk', 'There is a hot sale today')),
 (array([[0.]]), ('One hot enconding', 'i will have a chai latte with milk'))]