<img src="https://github.com/amandalemette/images/blob/e011da7260c032bae5c49e56a14ad97c13b8c679/BiMaster/bimaster.png?raw=true"  width=1000 height=80 />

# Professora

 - Amanda Lemette 
	 - prof.amanda@ica.ele.puc-rio.br
	 - [Linkedin](https://www.linkedin.com/in/amanda-lemette-brand%C3%A3o-83280918b)
  - [Youtube](https://www.youtube.com/c/AmandaLemette/featured)

<img src="https://github.com/amandalemette/images/blob/e011da7260c032bae5c49e56a14ad97c13b8c679/BiMaster/bimaster.png?raw=true"  width=1000 height=80 />

# Atividade 1

Desenvolva uma função que receba dois números como variáveis de entrada. Essa função irá retornar a informação de que o primeiro número é ou não é múltiplo do segundo número através de: 
- True 
- False


Exemplo:

```
Verifica(10,2)
>>  TRUE
```

 



In [2]:
def Verifica(n1,n2):
  if n1%n2 == 0:
    return True
  else: # n1%n2 != 0
    return False 

In [3]:
Verifica(10,2)

True

In [4]:
Verifica(13,4)

False

# Atividade 2

Em relação à função da atividade 2, modifique essa função de modo que se o número 1 for múltiplo do segundo número, a função além de retornar TRUE ela irá retornar o resultado da operação do número 1 dividido pelo número 2. 

In [9]:
def Verifica(n1,n2):
  if n1%n2 == 0:
    res = n1/n2
    return True,res 
  else: # n1%n2 != 0
    return False 

In [10]:
output = Verifica(10,4)

In [11]:
output

False

In [12]:
output = Verifica(25,5)

In [13]:
output

(True, 5.0)

In [15]:
output[0],output[1]

(True, 5.0)

In [16]:
out1,out2 = Verifica(25,5)

In [17]:
out1,out2

(True, 5.0)

In [18]:
out1,out2 = Verifica(25,3)

TypeError: ignored

# Atividade 3

Atualize mais uma vez a função da atividade 2, acrescentando a informação de que se o número não for múltiplo, a função irá retornar FALSE e também o resultado do num1 / num2 que não será um número inteiro. 

In [19]:
def Verifica(n1,n2):
  if n1%n2 == 0:
    res = n1/n2
    return True,res 
  else: # n1%n2 != 0
    return False, n1/n2 

In [20]:
out1,out2 = Verifica(25,3)

In [21]:
out1,out2

(False, 8.333333333333334)

# Atividade 4

Retorne à função desenvolvida na atividade 1 e a reescreva como função anônima. 

In [22]:
def Verifica(n1,n2):
  if n1%n2 == 0:
    return True
  else: # n1%n2 != 0
    return False 

nome da funcao = lambda var1,var2,var3: output da função

In [30]:
verifica_anon = lambda n1,n2: n1%n2 == 0

In [34]:
verifica_anon2 = lambda n1,n2: True if n1%n2 == 0 else False 

In [35]:
verifica_anon(20,10),verifica_anon2(30,4)

(True, False)

In [23]:
Verifica(20,10)

True

In [24]:
2==3

False

In [25]:
2==2

True

In [29]:
30%7 == 0

False

In [28]:
30%5 != 0

False

# Atividade 5

Faça uma função que recebe dois números inteiros e retorna uma lista com os números inteiros que estão no intervalo compreendido por eles.

In [36]:
'''
intervalo(10,2)
>> 3,4,5,6,7,8,9
'''

def intervalo(a,b):
  if a == b:
    return []
  elif a<b:
    res = []
    i = a+1
    while i < b:
      res.append(i)
      i = i + 1 # i += 1
    return res
  else: # a>b
    res = []
    i = b+1
    while i < a:
      res.append(i)
      i = i + 1
    return res 

In [39]:
intervalo(40,34)

[35, 36, 37, 38, 39]

# Atividade 6

Alguns amigos apostaram de modo independente na mega-sena, cada aposta foi de 6 números somente. 

Desenvolva uma função que confere se o seu bilhete é o ganhador ou se acertou ao menos algum número. 

A função deve retornar quantos números foram escolhidos corretamente e quais números. 

In [40]:
import numpy as np 

In [42]:
mega_sena = np.random.randint(1,61,6)
mega_sena

array([37, 33, 39, 10, 11,  8])

In [43]:
aposta = np.random.randint(1,61,6)
aposta

array([18, 49,  8, 10,  2, 59])

In [61]:
np.unique(aposta)

array([ 2,  8, 10, 18, 49, 59])

In [62]:
if len(np.unique(aposta)) != len(aposta):
  # verificar qual numero esta repetido

True

[random.choice](https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html)

In [63]:
from numpy.random import default_rng

In [64]:
rng = default_rng()
numbers = rng.choice(20, size=10, replace=False)

In [69]:
np.random.choice(range(1,61),size=6, replace=False)

array([43,  7,  2, 44, 30, 32])

In [66]:
numbers

array([ 6, 14,  3,  8, 11, 12,  2, 16, 13,  9])

In [45]:
acertos = []
for i in aposta:
  for j in mega_sena:
    if i == j:
      acertos.append(i)
      break

In [46]:
acertos

[8, 10]

In [50]:
def confere_aposta(ap):
  acertos = []
  for i in ap:
    for j in mega_sena:
      if i == j:
        acertos.append(i)
        break
  return len(acertos),acertos 

In [51]:
confere_aposta(aposta)

(2, [8, 10])

In [52]:
def confere_aposta2(ap):
  s = np.isin(ap,mega_sena)
  return len(ap[s]),ap[s]

In [53]:
confere_aposta2(aposta)

(2, array([ 8, 10]))

In [54]:
np.isin([2,3,4,5],[8,35,2,23])

array([ True, False, False, False])

In [58]:
lista = np.array([2,3,4,5])
lista

array([2, 3, 4, 5])

In [60]:
lista[np.isin([2,3,4,5],[8,35,2,23])]

array([2])

# Atividade 7

Crie uma função que recebe como variável de entrada uma lista e retorna outra lista contendo somente elementos do tipo *string*. 

In [70]:
def funcao_str(a):
  out = []
  for i in a:
    if type(i) == str:
      out.append(i)
  return out 

In [5]:
lista = ['a',3,65.-9,'bb','oi',34,True]

In [72]:
funcao_str(lista)

['a', 'bb', 'oi']

# Atividade 8

Inclua a função criada no item anterior em uma biblioteca chamada *biblioteca_listas* e importe essa biblioteca, testando depois a função criada. 

In [3]:
import biblioteca_listas as bl

In [6]:
bl.funcao_str(lista)

['a', 'bb', 'oi']